# Generated by Django 5.2 on 2025-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('sign', 'Вывеска'), ('banner', 'Баннер'), ('stand', 'Стенд')], max_length=20)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('material', models.CharField(choices=[('acrylic', 'Акрил'), ('pvc', 'ПВХ'), ('banner', 'Баннерная ткань')], max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
