# Generated by Django 5.2 on 2025-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_quoterequest_alter_portfolioitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Базовая цена в рублях за квадратный метр', max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='material',
            field=models.CharField(choices=[('banner_fabric', 'Баннерная ткань'), ('mesh', 'Сетка'), ('lightbox_film', 'Лайтбокс-плёнка'), ('pvc', 'ПВХ'), ('plastic', 'Пластик'), ('composite', 'Композит'), ('vinyl', 'Виниловая плёнка'), ('perforated_vinyl', 'Перфорированная плёнка'), ('uv_acrylic', 'УФ печать на акриле'), ('vinyl_gloss', 'Винил глянец'), ('vinyl_matte', 'Винил матовый'), ('vinyl_special', 'Винил спецэффект'), ('reinforced_banner', 'Прочный баннер'), ('blockout', 'Блок-аут'), ('acrylic', 'Акрил'), ('metal', 'Металл'), ('composite_led', 'Композит с подсветкой')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(choices=[('billboard', 'Биллборд'), ('stand', 'Штендер'), ('showcase', 'Оформление витрин'), ('car_wrap', 'Оклейка автомобилей'), ('facade_banner', 'Баннер на фасаде'), ('letters', 'Объёмные буквы')], max_length=20),
        ),
    ]
