# Generated by Django 5.2 on 2025-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_service_price_per_m2_alter_quoterequest_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.SlugField(default='default-code', max_length=30, verbose_name='Код услуги'),
        ),
    ]
