# Generated by Django 5.2 on 2025-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.SlugField(
                max_length=30,
                verbose_name='Код услуги',
                default='default-code',
                unique=False,
                null=True,  # если хочешь позже убрать — потом сделаем AlterField
            ),
        ),
    ]
