# Generated by Django 5.2 on 2025-05-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_acknowledge_existing_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.SlugField(default='default-code', max_length=30, verbose_name='Код услуги'),
        ),
    ]
