# Generated by Django 5.2 on 2025-05-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
