# Generated by Django 5.2 on 2025-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
