# Generated by Django 5.2 on 2025-05-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('pricing', '0004_service_price_per_m2_alter_quoterequest_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='Без имени', max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='phone', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pricing.service', verbose_name='Услуга'),
        ),
    ]
