# Generated by Django 5.2 on 2025-05-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_date_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.CharField(choices=[('banner_fabric', 'Баннерная ткань'), ('mesh', 'Сетка'), ('lightbox_film', 'Лайтбокс-плёнка'), ('pvc', 'ПВХ'), ('plastic', 'Пластик'), ('composite', 'Композит'), ('vinyl', 'Винил'), ('perforated_vinyl', 'Перфорированная плёнка'), ('uv_acrylic', 'УФ печать на акриле'), ('vinyl_gloss', 'Винил глянец'), ('vinyl_matte', 'Винил матовый'), ('vinyl_special', 'Винил спецэффект'), ('reinforced_banner', 'Прочный баннер'), ('blockout', 'Блок-аут'), ('acrylic', 'Акрил'), ('metal', 'Металл'), ('composite_led', 'Композит с подсветкой')], default='banner_fabric', max_length=30, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.service', verbose_name='Услуга'),
        ),
    ]
