# Generated by Django 5.2 on 2025-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_client_name_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Примерная стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.FloatField(default=1.0, verbose_name='Высота (м)'),
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.FloatField(default=1.0, verbose_name='Ширина (м)'),
        ),
    ]
